# Generated by Django 5.0.6 on 2025-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_paymentdetail_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='mob_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
